### ISSUE TITLE
Can't get tests to run in version 1.0.0

### ISSUE THREAD

**Issue by riezebosch** [slara/generator-reveal#82]
HEAD: f13b23e214715446780db4906af807ad6d5ec584

> generator-reveal@1.0.0 test /Users/.../generator-reveal-infosupport
> npm run coffeelint && istanbul test _mocha --report lcovonly -- ./test/*.coffee --require coffee-script/register --reporter spec --timeout 100000

> generator-reveal@1.0.0 coffeelint /Users/.../generator-reveal-infosupport
> coffeelint app/index.coffee slide/index.coffee test Gruntfile.coffee

  ✓ app/index.coffee
  ✓ slide/index.coffee
  ✓ test/test-app-file-creation.coffee
  ✓ test/test-load.coffee
  ✓ test/test-slide-file-creation.coffee
  ✓ Gruntfile.coffee

✓ Ok! » 0 errors and 0 warnings in 6 files

  Generator Reveal
    ✓ generates package.json with correct version
    ✓ updates .yo-rc.json config according to prompt input
    1) "after each" hook for "updates .yo-rc.json config according to prompt input"

  Generator Reveal
    ✓ can be imported without blowing up

  Sub-Generator Slide
    ✓ can be imported without blowing up

  Sub-Generator Slide
    default (no options passed)
      2) "before all" hook
    with --attributes option
      3) "before all" hook
    with --notes option
      4) creates html slide with notes
    with --markdown and --notes options
      5) creates markdown slide with notes
    with --markdown option
      6) creates markdown slide
    with --markdown and --attributes options
      7) creates markdown slide with attributes hash in list.json

  4 passing (299ms)
  7 failing

  1) Generator Reveal "after each" hook for "updates .yo-rc.json config according to prompt input":
     Error: ENOENT: no such file or directory, open 'Gruntfile.coffee'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at lint_generated_files (test/test-app-file-creation.coffee:16:12)
    at Context.<anonymous> (test/test-app-file-creation.coffee:40:9)
  

  2) Sub-Generator Slide default (no options passed) "before all" hook:

      Uncaught AssertionError: package.json did not match '/"version": "1.2.3"/'. Contained:

{
  "name": "icanhazconfig",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "grunt": "^1.0.0",
    "grunt-contrib-connect": "^1.0.2",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-jshint": "^1.1.0",
    "load-grunt-tasks": "^3.5.2", 
    "grunt-coffeelint": "0.0.16",
    "coffeelint": "^1.16.0"
  },
  "engines": {
    "node": ">=4"
  },
  "scripts": {
    "test": "grunt test"
  }
}

      + expected - actual

      -false
      +true
      
    at node_modules/yeoman-assert/index.js:111:5
    at Array.forEach (native)
    at Function.assert.fileContent (node_modules/yeoman-assert/index.js:98:9)
    at RunContext.<anonymous> (test/test-app-file-creation.coffee:86:24)
    at RunContext.<anonymous> (node_modules/yeoman-test/lib/run-context.js:108:10)
    at RevealGenerator.<anonymous> (node_modules/yeoman-generator/lib/index.js:387:10)
    at Queue.<anonymous> (node_modules/grouped-queue/lib/queue.js:68:12)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:79:43)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at Queue._exec (node_modules/grouped-queue/lib/queue.js:83:3)
  

  3) Sub-Generator Slide with --attributes option "before all" hook:

      Uncaught AssertionError: .yo-rc.json, no such file or directory
      + expected - actual

      -false
      +true
      
    at node_modules/yeoman-assert/index.js:46:12
    at Array.forEach (native)
    at Function.assert.file (node_modules/yeoman-assert/index.js:44:8)
    at node_modules/yeoman-assert/index.js:101:12
    at Array.forEach (native)
    at Function.assert.fileContent (node_modules/yeoman-assert/index.js:98:9)
    at RunContext.<anonymous> (test/test-app-file-creation.coffee:98:24)
    at RunContext.<anonymous> (node_modules/yeoman-test/lib/run-context.js:108:10)
    at RevealGenerator.<anonymous> (node_modules/yeoman-generator/lib/index.js:387:10)
    at Queue.<anonymous> (node_modules/grouped-queue/lib/queue.js:68:12)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:79:43)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (node_modules/grouped-queue/lib/queue.js:80:39)
    at Queue._exec (node_modules/grouped-queue/lib/queue.js:83:3)
  

  4) Sub-Generator Slide with --notes option creates html slide with notes:

      AssertionError: slides/html-with-notes.html, no such file or directory
      + expected - actual

      -false
      +true
      
    at node_modules/yeoman-assert/index.js:46:12
    at Array.forEach (native)
    at Function.assert.file (node_modules/yeoman-assert/index.js:44:8)
    at node_modules/yeoman-assert/index.js:101:12
    at Array.forEach (native)
    at Function.assert.fileContent (node_modules/yeoman-assert/index.js:98:9)
    at Context.<anonymous> (test/test-slide-file-creation.coffee:53:20)
  

  5) Sub-Generator Slide with --markdown and --notes options creates markdown slide with notes:

      AssertionError: slides/markdown-with-notes.md, no such file or directory
      + expected - actual

      -false
      +true
      
    at node_modules/yeoman-assert/index.js:46:12
    at Array.forEach (native)
    at Function.assert.file (node_modules/yeoman-assert/index.js:44:8)
    at node_modules/yeoman-assert/index.js:101:12
    at Array.forEach (native)
    at Function.assert.fileContent (node_modules/yeoman-assert/index.js:98:9)
    at Context.<anonymous> (test/test-slide-file-creation.coffee:71:20)
  

  6) Sub-Generator Slide with --markdown option creates markdown slide:

      AssertionError: slides/markdown-format.md, no such file or directory
      + expected - actual

      -false
      +true
      
    at node_modules/yeoman-assert/index.js:46:12
    at Array.forEach (native)
    at Function.assert.file (node_modules/yeoman-assert/index.js:44:8)
    at node_modules/yeoman-assert/index.js:101:12
    at Array.forEach (native)
    at Function.assert.fileContent (node_modules/yeoman-assert/index.js:98:9)
    at Context.<anonymous> (test/test-slide-file-creation.coffee:84:20)
  

  7) Sub-Generator Slide with --markdown and --attributes options creates markdown slide with attributes hash in list.json:

      AssertionError: slides/markdown-with-attributes.md, no such file or directory
      + expected - actual

      -false
      +true
      
    at node_modules/yeoman-assert/index.js:46:12
    at Array.forEach (native)
    at Function.assert.file (node_modules/yeoman-assert/index.js:44:8)
    at node_modules/yeoman-assert/index.js:101:12
    at Array.forEach (native)
    at Function.assert.fileContent (node_modules/yeoman-assert/index.js:98:9)
    at Context.<anonymous> (test/test-slide-file-creation.coffee:101:20)

**Comment by riezebosch** [comment]
I don't understand. If I fresh clone your repo it works but when I run it on my own fork on the same commit it fails...

**Comment by riezebosch** [comment]
A `git clean -fxd` did the trick. Sorry bothering you.

**Comment by janraasch** [comment]
No worries :)
